language: bash

sudo: required

before_script:
- "mysql -e 'create database node_mysql;'"

script:
- "mysql -e 'USE node_mysql;'"

mysql:
  adapter: mysql2
  username: root
  encoding: utf8
  database: node_mysql
