sudo: required

language: java

services:
  - docker

before_install:
  - docker pull asnagaraj/oracle-atg-11.1:v4
  
install:
  - docker run -v $(pwd)/atg:/opt/oracle/product/atgasnagaraj/oracle-atg-11.1:v4 /bin/bash -c ". ~/.bash_profile; git clone https://github.com/nagaseshadri/test-atg-module /root/test-atg-module; cd /root/test-atg-module; gradle --stacktrace gATGM"

script:
  - ls -l $(pwd)/atg 
  - gradle --stacktrace gATGM
