udo: required

language: bash

services:
  - docker

before_install:
  - mysql -e 'create database IF NOT EXISTS atg_core;'
  - mysql -e 'create database IF NOT EXISTS atg_ca;'

install:
  - docker pull asnagaraj/oracle-atg-11.1:v4

script:
  - docker run -v $TRAVIS_BUILD_DIR:/workspace/test-atg-module asnagaraj/oracle-atg-11.1:v4 /bin/bash -c ". ~/.bash_profile; cd /workspace/test-atg-module;  gradle --stacktrace gATGM"
