sudo: required

language: java

services:
  - docker

before_install:
  - docker pull asnagaraj/oracle-atg-11.1:v2
  - docker run asnagaraj/oracle-atg-11.1:v2 /bin/bash -c "git clone https://github.com/nagaseshadri/test-atg-module /root/test-atg-module; cd /root/test-atg-module; gradle gATGM"

script:
  - echo 'Done'
