sudo: required

language: java

services:
  - docker

before_install:
- docker pull asnagaraj/oracle-atg-11.1
- docker run -d asnagaraj/oracle-atg-11.1 /bin/bash -c "cd /root/test-atg-module; gradle gATGM"
- docker ps -a

script:
- gradle gATGM
