sudo: required

language: java

services:
  - docker

before_install:
- docker pull asnagaraj/oracle-atg-11.1:v2
- docker run -t -i asnagaraj/oracle-atg-11.1:v2 /bin/bash -c "cd /root/test-atg-module; gradle gATGM"
- docker ps -a

script:
- gradle gATGM 
