sudo: required

language: bash

services:
  - docker

install:
  - docker pull asnagaraj/oracle-atg-11.1:v4

before_script:
  - mysql --host=localhost --user=root --password=

script:
  - docker run -v $TRAVIS_BUILD_DIR:/workspace/test-atg-module asnagaraj/oracle-atg-11.1:v4 /bin/bash -c ". ~/.bash_profile; cd /workspace/test-atg-module;  gradle --stacktrace gATGM"

