sudo: required

language: java

services:
  - docker

install:
  - docker pull asnagaraj/oracle-atg-11.1:v4
  
install:
  - docker run -v $TRAVIS_BUILD_DIR/atg:/opt/oracle/product/atg asnagaraj/oracle-atg-11.1:v4 /bin/bash -c ". ~/.bash_profile; git clone https://github.com/nagaseshadri/test-atg-module /root/test-atg-module; cd /root/test-atg-module; gradle --stacktrace gATGM"

script:
  - ls -l $TRAVIS_BUILD_DIR/atg 
  - gradle --stacktrace gATGM
