language: node_js
node_js:
  - '0.6'
  - '0.8'
  - '0.10'
  - '0.12'
  - '1.0'
  - '1.8'
  - '2.0'
  - '2.5'
  - '3.0'

sudo: false

before_script:
- "mysql -e 'create database node_mysql;'"

script:
- "mysql -e 'USE node_mysql;'"

env:
  - MYSQL_HOST=localhost MYSQL_DATABASE=node_mysql MYSQL_USER=root MYSQL_PASSWORD=

mysql:
  adapter: mysql2
  username: root
  encoding: utf8
  database: node_mysql
